name: CI

on:
  pull_request:
    branches: [ "main", "development" ]

jobs:
  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run lint script with eslint
      run: npm run eslint . --ext .js,.ts